# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary

cc_binary(
    name = "awesome_substring",
    srcs = ["awesome_substring.cpp"]
)

cc_binary(
    name = "longest_substr_with_limit_ae",
    srcs = ["longest_substr_with_limit_ae.cpp"]
)

cc_binary(
    name = "flip_col_max_num_equal_rows",
    srcs = ["flip_col_max_num_equal_rows.cpp"]
)

cc_binary(
    name = "largest_merge_two_strings",
    srcs = ["largest_merge_two_strings.cpp"]
)
