# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary

cc_binary(
    name = "awesome_substring",
    srcs = ["awesome_substring.cpp"]
)

cc_binary(
    name = "longest_substr_with_limit_ae",
    srcs = ["longest_substr_with_limit_ae.cpp"]
)

